
# this is the set up code to make diagnosis screen
# here the buttons and visual features of the screen will be set.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(649, 749)
        MainWindow.setStyleSheet("background-color:rgb(237, 249, 255)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.uploadMask_btn = QtWidgets.QPushButton(self.centralwidget)
        self.uploadMask_btn.setGeometry(QtCore.QRect(220, 480, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.uploadMask_btn.setFont(font)
        self.uploadMask_btn.setStyleSheet("background-color: rgb(222, 222, 222)")
        self.uploadMask_btn.setObjectName("uploadMask_btn")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(120, 10, 411, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 130, 438, 227))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Welcom_example_Image = QtWidgets.QLabel(self.layoutWidget)
        self.Welcom_example_Image.setText("")
        self.Welcom_example_Image.setPixmap(QtGui.QPixmap("GUI_Images/WelcomImageExample.png"))
        self.Welcom_example_Image.setObjectName("Welcom_example_Image")
        self.verticalLayout_2.addWidget(self.Welcom_example_Image)
        self.image_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setItalic(True)
        self.image_label.setFont(font)
        self.image_label.setObjectName("image_label")
        self.verticalLayout_2.addWidget(self.image_label)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Welcom_example_mask = QtWidgets.QLabel(self.layoutWidget)
        self.Welcom_example_mask.setText("")
        self.Welcom_example_mask.setPixmap(QtGui.QPixmap("GUI_Images/WelcomImageExample2.png"))
        self.Welcom_example_mask.setObjectName("Welcom_example_mask")
        self.verticalLayout_3.addWidget(self.Welcom_example_mask)
        self.mask_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setItalic(True)
        self.mask_label.setFont(font)
        self.mask_label.setObjectName("mask_label")
        self.verticalLayout_3.addWidget(self.mask_label)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.Title_2 = QtWidgets.QLabel(self.centralwidget)
        self.Title_2.setGeometry(QtCore.QRect(30, 70, 631, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Title_2.setFont(font)
        self.Title_2.setObjectName("Title_2")
        self.uploadLarynx_btn = QtWidgets.QPushButton(self.centralwidget)
        self.uploadLarynx_btn.setGeometry(QtCore.QRect(220, 380, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.uploadLarynx_btn.setFont(font)
        self.uploadLarynx_btn.setStyleSheet("background-color: rgb(222, 222, 222)")
        self.uploadLarynx_btn.setObjectName("uploadLarynx_btn")
        self.imageName_label = QtWidgets.QTextBrowser(self.centralwidget)
        self.imageName_label.setGeometry(QtCore.QRect(220, 440, 171, 31))
        self.imageName_label.setObjectName("imageName_label")
        self.maskName_label = QtWidgets.QTextBrowser(self.centralwidget)
        self.maskName_label.setGeometry(QtCore.QRect(220, 540, 171, 31))
        self.maskName_label.setObjectName("maskName_label")
        self.Help_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Help_btn.setGeometry(QtCore.QRect(560, 20, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Help_btn.setFont(font)
        self.Help_btn.setStyleSheet("Background-color:rgb(255, 255, 127)")
        self.Help_btn.setObjectName("Help_btn")
        self.Continue_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Continue_btn.setGeometry(QtCore.QRect(210, 590, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Continue_btn.setFont(font)
        self.Continue_btn.setStyleSheet("background-color: rgb(153, 255, 170)")
        self.Continue_btn.setObjectName("Continue_btn")
        self.exit_btn = QtWidgets.QPushButton(self.centralwidget)
        self.exit_btn.setGeometry(QtCore.QRect(270, 670, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.exit_btn.setFont(font)
        self.exit_btn.setStyleSheet("Background-color:rgb(255, 66, 66)")
        self.exit_btn.setObjectName("exit_btn")
        self.back_btn = QtWidgets.QPushButton(self.centralwidget)
        self.back_btn.setGeometry(QtCore.QRect(10, 20, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.back_btn.setFont(font)
        self.back_btn.setStyleSheet("background-color:rgb(207, 207, 207)")
        self.back_btn.setObjectName("back_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 649, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.uploadMask_btn.setText(_translate("MainWindow", "Upload Larynx Mask"))
        self.Title.setText(_translate("MainWindow", "LPR Diagnostic system"))
        self.image_label.setText(_translate("MainWindow", "Image of the Larynx area"))
        self.mask_label.setText(_translate("MainWindow", "Image of the Larynx mask"))
        self.Title_2.setText(
            _translate("MainWindow", "Upload Larynx image and matching mask image like the example below:"))
        self.uploadLarynx_btn.setText(_translate("MainWindow", "Upload Larynx Image"))
        self.imageName_label.setHtml(_translate("MainWindow",
                                                "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                "p, li { white-space: pre-wrap; }\n"
                                                "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                                "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.maskName_label.setHtml(_translate("MainWindow",
                                               "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                               "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                               "p, li { white-space: pre-wrap; }\n"
                                               "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
                                               "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.Help_btn.setText(_translate("MainWindow", "Help"))
        self.Continue_btn.setText(_translate("MainWindow", "Make Diagnosis"))
        self.exit_btn.setText(_translate("MainWindow", "Exit"))
        self.back_btn.setText(_translate("MainWindow", "Back"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
